=== zhangyajunsir/abInject/app/jsrccb.common/resources/xsd/ibm_cbod_header.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema 
	xmlns:xs="http://www.w3.org/2001/XMLSchema"
	xmlns="http://www.w3school.com"
	targetNamespace="http://www.w3school.com"  
	elementFormDefault="qualified">

	<xs:element name="interfaces">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="alias-mappings" minOccurs="1" maxOccurs="1">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="mapping" type="aliasMappingType" minOccurs="0" maxOccurs="unbounded"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="metadatas-pool" minOccurs="1" maxOccurs="1">
					<xs:complexType>
						<xs:sequence minOccurs="0" maxOccurs="unbounded">
							<xs:element name="variable-field" type="variableFieldType" minOccurs="0" maxOccurs="unbounded"/>
							<xs:element name="fixed-field"    type="fixedFieldType"    minOccurs="0" maxOccurs="unbounded"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="interface" minOccurs="1" maxOccurs="1">
					<xs:complexType>
						<xs:sequence>
							<!-- 请求节点 -->
							<xs:element name="request" minOccurs="1" maxOccurs="1">
								<xs:complexType>
									<xs:sequence minOccurs="0" maxOccurs="unbounded">
										<xs:element name="fixed-field"    type="fixedFieldType"    minOccurs="0" maxOccurs="unbounded"/>
										<xs:element name="field"          type="referFieldType"    minOccurs="0" maxOccurs="unbounded"/>
										<xs:element name="object"         type="objectType"        minOccurs="0" maxOccurs="unbounded"/>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<!-- 应答节点 -->
							<xs:element name="response" minOccurs="1" maxOccurs="1">
								<xs:complexType>
									<xs:sequence minOccurs="0" maxOccurs="unbounded">
										<xs:element name="fixed-field"    type="fixedFieldType"    minOccurs="0" maxOccurs="unbounded"/>
										<xs:element name="field"          type="referFieldType"    minOccurs="0" maxOccurs="unbounded"/>
										<xs:element name="object"         type="objectType"        minOccurs="0" maxOccurs="unbounded"/>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
						<xs:attribute name="name" type="nameType" use="required"/>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:simpleType name="nameType">
		<xs:restriction base="xs:string">
			<xs:pattern value="[a-zA-Z0-9_]{0,20}"/>
		</xs:restriction>
	</xs:simpleType>
	<!-- 基础元信息名称类型定义 -->
	<xs:simpleType name="fieldNameType">
		<xs:restriction base="xs:string">
			<xs:pattern value="[a-zA-Z0-9_\.]{0,50}"/>
		</xs:restriction>
	</xs:simpleType>
	<!-- 基础元信息别名类型定义 -->
	<xs:simpleType name="fieldAliasType">
		<xs:restriction base="xs:string">
			<xs:pattern value="[a-zA-Z0-9_]{0,20}"/>
		</xs:restriction>
	</xs:simpleType>
	<!-- 基础元信息字段描述定义 -->
	<xs:simpleType name="fieldDescType">
		<xs:restriction base="xs:string">
			<xs:pattern value="\w{0,20}"/>
		</xs:restriction>
	</xs:simpleType>
	<!-- 基础元信息字段描述定义 -->
	<xs:simpleType name="fieldLenType">
		<xs:restriction base="xs:integer"/>
	</xs:simpleType>
	<!-- 基础元信息字段Java类型定义 -->
	<xs:simpleType name="fieldClassType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="String"/>
			<xs:enumeration value="Integer"/>
			<xs:enumeration value="BigDecimal"/>
			<xs:enumeration value="Date"/>
			<xs:enumeration value="ByteBuffer"/>
			<xs:enumeration value="Money"/>
		</xs:restriction>
	</xs:simpleType>
	<!-- 基础元信息字段允许为null类型定义 -->
	<xs:simpleType name="fieldAllowNullType">
		<xs:restriction base="xs:boolean"/>
	</xs:simpleType>
	<!-- 基础元信息字段允许为填充样式类型定义 -->
	<xs:simpleType name="fieldFillStyleType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="right"/>
			<xs:enumeration value="left"/>
		</xs:restriction>
	</xs:simpleType>
	<!-- 编码属性定义 -->
	<xs:simpleType name="encodingType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="GBK"/>
			<xs:enumeration value="GB2312"/>
			<xs:enumeration value="ISO8859-1"/>
			<xs:enumeration value="UTF-8"/>
			<xs:enumeration value="Big5"/>
			<xs:enumeration value="EBCDIC"/>
		</xs:restriction>
	</xs:simpleType>
	<!-- 别名类型 -->
	<xs:complexType name="aliasMappingType">
		<xs:attribute name="alias" type="xs:string"/>
		<xs:attribute name="real" type="xs:string"/>
		<xs:attribute name="domain">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:enumeration value="global"/>
					<xs:enumeration value="inner"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
	</xs:complexType>
	<!-- 数据类型 -->
	<xs:simpleType name="valueModeType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="constant"/>
			<xs:enumeration value="default"/>
			<xs:enumeration value="user"/>
			<xs:enumeration value="inner"/>
		</xs:restriction>
	</xs:simpleType>
	
	<!-- 交易数据对象名称属性定义 -->
	<xs:simpleType name="objectNameType">
		<xs:restriction base="xs:string"/>
	</xs:simpleType>
	<!-- 交易数据对象类型属性定义 -->
	<xs:simpleType name="objectTypeType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="bean"/>
			<xs:enumeration value="form"/>
		</xs:restriction>
	</xs:simpleType>
	<!-- 交易数据对象描述属性定义 -->
	<xs:simpleType name="objectDescType">
		<xs:restriction base="xs:string">
			<xs:minLength value="0"/>
			<xs:maxLength value="200"/>
		</xs:restriction>
	</xs:simpleType>
	<!-- 交易数据对象编码属性定义 -->
	<xs:simpleType name="objectEncodingType">
		<xs:restriction base="encodingType"/>
	</xs:simpleType>
	<!-- 交易数据对象包装类属性定义 -->
	<xs:simpleType name="objectWrapClassType">
		<xs:restriction base="xs:string"/>
	</xs:simpleType>

	<!-- 定长字段节点定义 -->
	<xs:complexType name="fixedFieldType">
		<xs:attribute name="name"       type="fieldNameType"      use="required"/>
		<xs:attribute name="alias"      type="fieldAliasType"     use="optional"/>
		<xs:attribute name="desc"       type="fieldDescType"                     default="字段描述"/>
		<xs:attribute name="encoding"   type="encodingType"       use="optional" default="UTF-8"/>
		<xs:attribute name="fill-style" type="fieldFillStyleType" use="optional"/>
		<xs:attribute name="len"        type="fieldLenType"       use="required"/>
		<xs:attribute name="class"      type="fieldClassType"     use="required"/>
		<xs:attribute name="value-mode" type="valueModeType"/>
		<xs:attribute name="value"      type="xs:string"/>
		<xs:attribute name="fill-char"  type="xs:string"          use="optional"/>
		<xs:attribute name="format"     type="xs:string"          use="optional"/>
		<xs:attribute name="scale"      type="xs:integer"         use="optional"/>
	</xs:complexType>
	<!-- 不定长字段节点定义 -->
	<xs:complexType name="variableFieldType">
		<xs:attribute name="name"       type="fieldNameType"      use="required"/>
		<xs:attribute name="alias"      type="fieldAliasType"     use="optional"/>
		<xs:attribute name="desc"       type="fieldDescType"                     default="字段描述"/>
		<xs:attribute name="encoding"   type="encodingType"       use="optional" default="UTF-8"/>
		<xs:attribute name="max-len"    type="fieldLenType"       use="required"/>
		<xs:attribute name="min-len"    type="fieldLenType"       use="required"/>
		<xs:attribute name="allow-null" type="fieldAllowNullType" use="required"/>
		<xs:attribute name="class"      type="fieldClassType"     use="required"/>
		<xs:attribute name="value-mode" type="valueModeType"/>
		<xs:attribute name="value"      type="xs:string"/>
		<xs:attribute name="format"     type="xs:string"          use="optional"/>
		<xs:attribute name="scale"      type="xs:integer"         use="optional"/>
	</xs:complexType>
	<!-- 交易数据对象字段引用定义 -->
	<xs:complexType name="referFieldType">
		<xs:sequence minOccurs="0" maxOccurs="99">
			<xs:element name="mapping" minOccurs="0" maxOccurs="unbounded">
				<xs:complexType>
					<xs:attribute name="express-id"  type="xs:integer"     use="required"/>
					<xs:attribute name="trade-code"  type="xs:string"      use="required"/>
					<xs:attribute name="value"       type="xs:string"      use="required"/>
					<xs:attribute name="value-mode"  type="valueModeType"/>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
		<xs:attribute name="name"       type="fieldNameType"      use="required"/>
		<xs:attribute name="alias"      type="fieldAliasType"     use="required"/>
		<xs:attribute name="desc"       type="fieldDescType"                     default="引用字段描述"/>
		<xs:attribute name="value"      type="xs:string"          use="optional"/>
		<xs:attribute name="value-mode" type="valueModeType"/>
	</xs:complexType>
	<!-- 交易数据对象定义 -->
	<xs:complexType name="objectType">
		<xs:sequence minOccurs="0" maxOccurs="99">
			<xs:element name="field"          type="referFieldType"       minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="variable-field" type="variableFieldType"    minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="fixed-field"    type="fixedFieldType"       minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute name="name"       type="objectNameType"      use="required"/>
		<xs:attribute name="alias"      type="fieldAliasType"      use="optional"/>
		<xs:attribute name="desc"       type="objectDescType"                     default="对象描述"/>
		<xs:attribute name="encoding"   type="encodingType"        use="optional" default="UTF-8"/>
		<xs:attribute name="value"      type="xs:string"           use="optional"/>
		<xs:attribute name="type"       type="objectTypeType"      use="required"/>
		<xs:attribute name="wrap-class" type="objectWrapClassType" use="required"/>
	</xs:complexType>
</xs:schema>

=== zhangyajunsir/abInject/app/jsrccb.common/resources/interfaces/headers/cbod_optl.xml
<?xml version="1.0" encoding="UTF-8"?>
<interfaces 
	xmlns="http://www.w3school.com" 
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
	xsi:schemaLocation="http://www.w3school.com ../../xsd/ibm_cbod_header.xsd">
	<!-- 别名映射 -->
	<alias-mappings>
		<!-- domain取值inner和global,inner仅在接口内有效，global在全局有效,在不设置domain时默认为inner -->
		<mapping alias="String"         real="java.lang.String"              domain="global"/>
		<mapping alias="Date"           real="java.util.Date"                domain="global"/>
		<mapping alias="BigDecimal"     real="java.math.BigDecimal"          domain="global"/>
		<mapping alias="Integer"        real="java.lang.Integer"             domain="global"/>
		<mapping alias="Byte"           real="java.lang.Byte"                domain="global"/>
		<mapping alias="ByteBuffer"     real="java.nio.ByteBuffer"           domain="global"/>
		<mapping alias="StringArray"    real="[Ljava.lang.String"            domain="global"/>
		<mapping alias="ObjectArray"    real="[Ljava.lang.Object"            domain="global"/>
		<mapping alias="List"           real="java.util.ArrayList"           domain="global"/>
		<mapping alias="Map"            real="java.util.HashMap"             domain="global"/>
		<mapping alias="PagingDM"       real="jsrccb.common.dm.PageDM"/>
		<mapping alias="ChargeDM"       real="jsrccb.common.dm.ChargeDM"/>
		<mapping alias="AuthDM"         real="jsrccb.common.dm.AuthDM"/>
	</alias-mappings>
	<!-- 元信息池 -->
	<metadatas-pool>
		<fixed-field name="INM_SPV_A"          encoding="EBCDIC"    len="12"  fill-style="right" class="String"     alias="" desc="授权A级主管代号"/>
		<fixed-field name="INM_SPV_B"          encoding="EBCDIC"    len="12"  fill-style="right" class="String"     alias="" desc="授权B级主管代号"/>
		<fixed-field name="INM_LCL_OR_RSN"     encoding="EBCDIC"    len="20"  fill-style="right" class="String"     alias="" desc="LOCAL授权理由"/>
		<fixed-field name="INM_HST_OR_RSN"     encoding="EBCDIC"    len="20"  fill-style="right" class="String"     alias="" desc="HOST授权理由"/>
		<fixed-field name="INM_VERIFY_TELLER"  encoding="EBCDIC"    len="12"  fill-style="right" class="String"     alias="" desc="复核柜员"/>
		<fixed-field name="INM_OFFLINE_TX_NO"  encoding="EBCDIC"    len="19"  fill-style="right" class="String"     alias="" desc="端末系统流水编号"/>
		<fixed-field name="INM_PAGE_STA_KEY"   encoding="EBCDIC"    len="64"  fill-style="right" class="String"     alias="" desc="上页第一笔资料的KEY值"/>
		<fixed-field name="INM_PAGE_END_KEY"   encoding="EBCDIC"    len="64"  fill-style="right" class="String"     alias="" desc="该页最后一笔资料的KEY值"/>
		<fixed-field name="INM_PAGE_UP_DOWN"   encoding="EBCDIC"    len="1"   fill-style="right" class="String"     alias="" desc="跳页指示"/>
		<fixed-field name="INM_TIMESTAMP"      encoding="ISO8859-1" len="8"   fill-style="right" class="ByteBuffer" alias="" desc="TIMESTAMP"/>
		<fixed-field name="INM_JOB_ID"         encoding="EBCDIC"    len="4"   fill-style="right" class="String"     alias="" desc="整批输入的作业代号"/>
		<fixed-field name="INM_BATCH_NO"       encoding="EBCDIC"    len="4"   fill-style="left"  class="Integer"    alias="" desc="整批输入批号"/>
		<fixed-field name="INM_PSN"            encoding="EBCDIC"    len="7"   fill-style="left"  class="Integer"    alias="" desc="处理序号"/>
		<fixed-field name="INM_UPD_INT"        encoding="EBCDIC"    len="1"   fill-style="right" class="String"     alias="" desc="更新准备"/>
		<fixed-field name="INM_SPV_PWD"        encoding="EBCDIC"    len="32"  fill-style="right" class="String"     alias="" desc="AB级主管PINBlock"/>
		<fixed-field name="INM_SEC_OFFSET"     encoding="ISO8859-1" len="2"   fill-style="left"  class="Integer"    alias="" desc="加解密字段位移"     value-mode="inner"/>
		<fixed-field name="INM_SEC_LENGTH"     encoding="ISO8859-1" len="2"   fill-style="left"  class="Integer"    alias="" desc="加解密字段长度"     value-mode="inner"/>
		<fixed-field name="INM_DVV_VALUE"      encoding="EBCDIC"    len="3"   fill-style="right" class="String"     alias="" desc=""/>
		<fixed-field name="INM_IBS_CLEAR_DATE" encoding="EBCDIC"    len="8"   fill-style="right" class="String"     alias="" desc="外系统对帐日期"/>
		<fixed-field name="INM_N_MAC_OFFSET"   encoding="ISO8859-1" len="2"   fill-style="left"  class="Integer"    alias="" desc="压码资料起始位置"   value-mode="inner"/>
		<fixed-field name="INM_N_MAC_LL"       encoding="ISO8859-1" len="2"   fill-style="left"  class="Integer"    alias="" desc="压码资料长度"       value-mode="inner"/>
		<fixed-field name="INM_N_MAC_VALUE"    encoding="EBCDIC"    len="16"  fill-style="right" class="String"     alias="" desc="压码值"             value-mode="inner"/>
		<fixed-field name="INM_AUT_REQ_NO"     encoding="EBCDIC"    len="24"  fill-style="right" class="String"     alias="" desc="跨机构授权复核处理号"/>
		<fixed-field name="INM_CONFIRM_FLG"    encoding="EBCDIC"    len="1"   fill-style="right" class="String"     alias="" desc="预警功能的柜员确认标志"/>
		<fixed-field name="INM_SVR_TRIAL_FLG"  encoding="EBCDIC"    len="1"   fill-style="right" class="String"     alias="" desc=""/>
		<fixed-field name="INM_CHRG_MOD"       encoding="EBCDIC"    len="1"   fill-style="right" class="String"     alias="" desc=""/>
		<fixed-field name="INM_CASH_TRN_FLG"   encoding="EBCDIC"    len="1"   fill-style="right" class="String"     alias="" desc=""/>
		<fixed-field name="INM_CHRG_ACCT_NO"   encoding="EBCDIC"    len="28"  fill-style="right" class="String"     alias="" desc=""/>
		<fixed-field name="INM_OVERRID_REASON" encoding="EBCDIC"    len="42"  fill-style="right" class="String"     alias="" desc=""/>
		<fixed-field name="INM_CASH_PROJ_NO"   encoding="EBCDIC"    len="8"   fill-style="right" class="String"     alias="" desc=""/>
		<fixed-field name="INM_FEECOD_COUNTS"  encoding="EBCDIC"    len="1"   fill-style="left"  class="String"     alias="" desc="" fill-char="0"/>
		<fixed-field name="INM_CHRG_COD"       encoding="EBCDIC"    len="8"   fill-style="right" class="String"     alias="" desc=""/>
		<fixed-field name="INM_DSCT_RAT"       encoding="EBCDIC"    len="15"  fill-style="left"  class="String"     alias="" desc="" fill-char="0" value-mode="default" value="0"/>
		<fixed-field name="INM_CUST_CHRGE_FEE" encoding="EBCDIC"    len="15"  fill-style="left"  class="String"     alias="" desc="" fill-char="0"/>
		<fixed-field name="INM_ENC_DEV_ID"     encoding="EBCDIC"    len="16"  fill-style="right" class="String"     alias="" desc=""/>

		<fixed-field name="OPM_TX_LOG_NO"      encoding="EBCDIC"    len="19"  fill-style="right" class="String"     alias="" desc="TXLOG编号"/>
		<fixed-field name="OPM_TIMESTAMP"      encoding="ISO8859-1" len="8"   fill-style="left"  class="ByteBuffer" alias="" desc="TIMESTAMP"/>
		<fixed-field name="OPM_MSG_SEQ"        encoding="ISO8859-1" len="2"   fill-style="left"  class="Integer"    alias="" desc="输出讯息序号"/>
		<fixed-field name="OPM_MSG_CODE"       encoding="EBCDIC"    len="5"   fill-style="right" class="String"     alias="" desc="输出讯息码"/>
		<fixed-field name="OPM_MSG_TXT"        encoding="EBCDIC"    len="42"  fill-style="right" class="String"     alias="" desc="输出讯息应用内容"/>
		<fixed-field name="OPM_MSG_DB_TXT"     encoding="EBCDIC"    len="35"  fill-style="right" class="String"     alias="" desc="输出讯息CMMSGMSG中的内容"/>
		<fixed-field name="OPM_PAGE_STA_KEY"   encoding="EBCDIC"    len="64"  fill-style="right" class="String"     alias="" desc="该页第一笔资料KEY值"/>
		<fixed-field name="OPM_PAGE_END_KEY"   encoding="EBCDIC"    len="64"  fill-style="right" class="String"     alias="" desc="该页最后一笔资料KEY值"/>
		<fixed-field name="OPM_PAGE_NO_DATA"   encoding="EBCDIC"    len="1"   fill-style="right" class="String"     alias="" desc="是否最后一笔资料"/>
		<fixed-field name="OPM_PSN"            encoding="ISO8859-1" len="7"   fill-style="left"  class="Integer"    alias="" desc="处理序号"/>
		<fixed-field name="OPM_TRIG_TX_ID"     encoding="EBCDIC"    len="9"   fill-style="right" class="String"     alias="" desc="启动下一交易代号"/>
		<fixed-field name="OPM_AUT_REQ_NO"     encoding="EBCDIC"    len="24"  fill-style="right" class="String"     alias="" desc="跨机构授权复核处理号"/>
		<fixed-field name="OPM_AUT_TYP"        encoding="EBCDIC"    len="2"   fill-style="right" class="String"     alias="" desc="跨机构授权复核处理类型"/>
		<fixed-field name="OPM_AUT_FIX_BRH"    encoding="EBCDIC"    len="9"   fill-style="right" class="String"     alias="" desc="跨机构授权复核处理机构"/>
	</metadatas-pool>
	<interface name="optl">
		<request>
			<field  name="INM_SPV_A"            alias="INM_SPV_A"                 value="context.authDM.(#this == null ? null : #this.authTellerA)"/>
			<field  name="INM_SPV_B"            alias="INM_SPV_B"                 value="context.authDM.(#this == null ? null : #this.authTellerB)"/>
			<field  name="INM_LCL_OR_RSN"       alias="INM_LCL_OR_RSN"            value="context.authDM.(#this == null ? null : #this.reason.(#this == null || #this.size == 0 ? null : #this.get(0)))"/>
			<field  name="INM_HST_OR_RSN"       alias="INM_HST_OR_RSN"            value="context.authDM.(#this == null ? null : #this.reason.(#this == null || #this.size == 0 ? null : #this.get(0)))"/>
			<field  name="INM_VERIFY_TELLER"    alias="INM_VERIFY_TELLER"         value="context.reviewDM.(#this == null ? null : #this.verifyTeller)"/>
			<field  name="INM_OFFLINE_TX_NO"    alias="INM_OFFLINE_TX_NO"         value="innerArea.OFFLINE_TX_NO"/>
			<object name="INM_PAGE_CTL"         alias=""            desc="翻页对象"        type="bean"      wrap-class="Map"     value="context.pagingDM.(#this == null ? null : #this.pageContext)">
				<field name="staKey"            alias="INM_PAGE_STA_KEY"/>
				<field name="endKey"            alias="INM_PAGE_END_KEY"/>
				<field name="action"            alias="INM_PAGE_UP_DOWN"/>
			</object>
			<field  name="INM_TIMESTAMP"        alias="INM_TIMESTAMP">
				<mapping express-id="0" trade-code="21114" value="tempArea.TIMESTAMP"/>
				<mapping express-id="0" trade-code="21302" value="tempArea.TIMESTAMP"/>
			</field>
			<field  name="INM_JOB_ID"           alias="INM_JOB_ID"/>
