=== zhangyajunsir/abInject/app/jsrccb.common/resources/xsd/print.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema 
	xmlns:xs="http://www.w3.org/2001/XMLSchema"
	xmlns="http://www.w3school.com"
	targetNamespace="http://www.w3school.com" 
	elementFormDefault="qualified">

	<xs:element name="print-cfg">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="proofs" minOccurs="1" maxOccurs="1">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="proof" type="proofType" minOccurs="0" maxOccurs="unbounded"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="commit-special" minOccurs="1" maxOccurs="1">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="commit-code" type="commitCodeType" minOccurs="0" maxOccurs="unbounded"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="reports" minOccurs="1" maxOccurs="1">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="report"   type="reportType" minOccurs="0" maxOccurs="unbounded"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	
	<xs:complexType name="proofType">
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attribute name="name"     type="nameType"/>
				<xs:attribute name="type"     type="printType"/>
				<xs:attribute name="preview"  type="xs:boolean"/>
				<xs:attribute name="must"     type="xs:boolean"/>
				<xs:attribute name="reprint"  type="xs:boolean"/>
				<xs:attribute name="template" type="xs:string"/>
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
	<xs:simpleType name="nameType">
		<xs:restriction base="xs:string">
			<!--xs:pattern value="[a-zA-Z0-9_]{0,50}"/-->
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="printType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="text"/>
			<xs:enumeration value="pdf"/>
			<xs:enumeration value="text2File"/>
			<xs:enumeration value="text2LP"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:complexType name="commitCodeType">
		<xs:attribute name="name"     type="nameType"/>
		<xs:attribute name="skip"     type="splitType" use="optional"/>
		<xs:attribute name="add"      type="splitType" use="optional"/>
		<xs:attribute name="grid"     type="splitType" use="optional"/>
	</xs:complexType>
	<xs:simpleType name="splitType">
		<xs:restriction base="xs:string">
			<xs:pattern value="[a-zA-Z0-9_,]{0,200}"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:complexType name="reportType">
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attribute name="name"          type="nameType"/>
				<xs:attribute name="type"          type="printType"/>
				<xs:attribute name="preview"       type="xs:boolean"/>
				<xs:attribute name="page-size"     type="xs:integer" use="optional"/>
				<xs:attribute name="head-template" type="xs:string"  use="optional"/>
				<xs:attribute name="body-template" type="xs:string"  use="optional"/>
				<xs:attribute name="foot-template" type="xs:string"  use="optional"/>
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>


</xs:schema>

=== zhangyajunsir/abInject/app/jsrccb.common/resources/config/print.xml
<?xml version="1.0" encoding="UTF-8"?>
<print-cfg 
	xmlns="http://www.w3school.com" 
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
	xsi:schemaLocation="http://www.w3school.com ../xsd/print.xsd">
	<proofs>
		<!-- 单个凭证配置，老配置中00和01不需要配置 -->
		<proof name="FCMAEA01" type="text"  preview="true" must="false" reprint="true" template="rccb/dsr/f/FCMAEA01f.fmt">会计分录明细</proof>
		<proof name="PZZB5074" type="text"  preview="true" must="false" reprint="true" template="rccb/dsr/f/PZZB5074f.fmt">个人业务现金存款凭证</proof>
		<proof name="PEC39221" type="text"  preview="true" must="false" reprint="true" template="rccb/dsr/f/PEC39221f.fmt">公有客户群维护凭证</proof>
		<proof name="510311o" type="text"  preview="true" must="false" reprint="true" template="rccb/dsr/f/510311of.fmt">电子缴款凭证打印</proof>
		<proof name="df_800015o" type="text"  preview="true" must="false" reprint="true" template="rccb/dsr/f/df_800015of.fmt"> 电费托收凭证</proof>
		<proof name="df_8000152o" type="text"  preview="true" must="false" reprint="true" template="rccb/dsr/f/df_8000152of.fmt">电费发票凭证</proof>
		<proof name="df_8000150o" type="text"  preview="true" must="false" reprint="true" template="rccb/dsr/f/df_8000150of.fmt">发票联</proof>
		<proof name="ffines_036510o" type="text"  preview="true" must="false" reprint="true" template="ffines_036510of.fmt">溧水罚没款划款凭证</proof>
		<proof name="met_513036o" type="text"  preview="true" must="false" reprint="true" template="met_513036of.fmt">预售单号提货凭证</proof>
	</proofs>
	
	<commit-special>
		<!-- 特殊主通讯，跳过、新增凭证，表格连打方式打印 -->
		<commit-code name="CR0507401" skip="SCR50740" add="PZZB5074,FCMAEA01" grid=""/>
		<commit-code name="000012510311" skip="" add="" grid="510311o"/>
		<commit-code name="electf800015" skip="" add="df_800015o" grid="510311o"/>
	</commit-special>
	
	<reports>
		<!-- 报表凭证配置 -->
		<report name="table_name_lp" type="text2LP" preview="true" page-size="10" head-template="/dsr/f/table_nameHf.fmt" body-template="/dsr/f/table_nameDf.fmt" foot-template="/dsr/f/table_nameFf.fmt">表格流水打印</report>
		<report name="table_KQ51625表格" type="text" preview="true" page-size="10" head-template="jsrccb.trade.afa/dsr/f/table_KQ51625表格Hf.fmt" body-template="jsrccb.trade.afa/dsr/f/table_KQ51625表格Df.fmt" foot-template="jsrccb.trade.afa/dsr/f/table_KQ51625表格Ff.fmt">柜面打印</report>
		<report name="table_KQ51625表格_lp" type="text2LP" preview="true" page-size="10" head-template="jsrccb.trade.afa/dsr/f/table_KQ51625表格_lpHf.fmt" body-template="jsrccb.trade.afa/dsr/f/table_KQ51625表格_lpDf.fmt" foot-template="jsrccb.trade.afa/dsr/f/table_KQ51625表格_lpFf.fmt">表格流水打印</report>
		<report name="table_31701_大额" type="text" preview="true" page-size="10" head-template="table_31701_大额Hf.fmt" body-template="table_31701_大额Df.fmt" foot-template="table_com_end.fmt">柜面打印</report>
		<report name="table_31701_大额_lp" type="text2LP" preview="true" page-size="10" head-template="table_31701_大额_lpHf.fmt" body-template="table_31701_大额_lpDf.fmt" foot-template="table_com_end.fmt">表格流水打印</report>

	</reports>
</print-cfg>
