=== zhangyajunsir/abInject/app/cn.com.agree.ab.common/resources/xsd/lenovo_sop.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema 
	xmlns:xs="http://www.w3.org/2001/XMLSchema"
	xmlns="http://www.w3school.com"
	targetNamespace="http://www.w3school.com" 
	elementFormDefault="qualified">

	<xs:element name="interfaces">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="alias-mappings" minOccurs="1" maxOccurs="1">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="mapping" type="aliasType" minOccurs="0" maxOccurs="unbounded"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="metadatas-pool" minOccurs="1" maxOccurs="1">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="variable-field" type="variableFieldType" minOccurs="0" maxOccurs="unbounded"/>
							<xs:element name="fixed-field"    type="fixedFieldType"    minOccurs="0" maxOccurs="unbounded"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="interface" minOccurs="1" maxOccurs="1">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="request"   type="busisType"/>
							<xs:element name="response"  type="busisType"/>
							<xs:element name="exception" type="busisType"/>
						</xs:sequence>
						<xs:attribute name="name" type="nameType" use="required"/>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<!-- 别名类型 -->
	<xs:complexType name="aliasType">
		<xs:attribute name="alias" type="xs:string"/>
		<xs:attribute name="real"  type="xs:string"/>
		<xs:attribute name="domain">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:enumeration value="global"/>
					<xs:enumeration value="inner"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
	</xs:complexType>
	<!-- 定长字段节点定义 -->
	<xs:complexType name="fixedFieldType">
		<xs:attribute name="name"       type="fieldNameType"      use="required"/>
		<xs:attribute name="alias"      type="fieldAliasType"     use="optional"/>
		<xs:attribute name="desc"       type="fieldDescType"                     default="字段描述"/>
		<xs:attribute name="encoding"   type="encodingType"       use="optional" default="UTF-8"/>
		<xs:attribute name="fill-style" type="fieldFillStyleType" use="optional"/>
		<xs:attribute name="len"        type="fieldLenType"       use="required"/>
		<xs:attribute name="class"      type="fieldClassType"     use="required"/>
		<xs:attribute name="value-mode" type="valueModeType"/>
		<xs:attribute name="value"      type="xs:string"/>
	</xs:complexType>
	<!-- 不定长字段节点定义 -->
	<xs:complexType name="variableFieldType">
		<xs:attribute name="name"       type="fieldNameType"      use="required"/>
		<xs:attribute name="alias"      type="fieldAliasType"     use="optional"/>
		<xs:attribute name="desc"       type="fieldDescType"                     default="字段描述"/>
		<xs:attribute name="encoding"   type="encodingType"       use="optional" default="UTF-8"/>
		<xs:attribute name="max-len"    type="fieldLenType"       use="required"/>
		<xs:attribute name="min-len"    type="fieldLenType"       use="required"/>
		<xs:attribute name="allow-null" type="fieldAllowNullType" use="required"/>
		<xs:attribute name="class"      type="fieldClassType"     use="required"/>
		<xs:attribute name="value-mode" type="valueModeType"/>
		<xs:attribute name="value"      type="xs:string"/>
	</xs:complexType>
	<!-- 不同类型报文，需要定义不同的busisType -->
	<xs:complexType name="busisType">
		<xs:sequence>
			<xs:element name="sys">
				<xs:complexType>
					<xs:attribute name="inline" type="inlineType" use="required"/>
				</xs:complexType>
			</xs:element>
			<xs:element name="com">
				<xs:complexType>
					<xs:attribute name="inline" type="inlineType" use="required"/>
				</xs:complexType>
			</xs:element>
			<xs:element name="busis">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="busi" minOccurs="1" maxOccurs="2">
							<xs:complexType>
								<xs:sequence>
									<xs:element name="header">
										<xs:complexType>
											<xs:attribute name="inline" type="inlineType" use="required"/>
										</xs:complexType>
									</xs:element>
									<xs:sequence minOccurs="0" maxOccurs="unbounded">
										<xs:element name="field"          type="objectReferFieldType" minOccurs="0" maxOccurs="unbounded"/>
										<xs:element name="variable-field" type="variableFieldType"    minOccurs="0" maxOccurs="unbounded"/>
										<xs:element name="fixed-field"    type="fixedFieldType"       minOccurs="0" maxOccurs="unbounded"/>
										<xs:element name="object"         type="objectType"           minOccurs="0" maxOccurs="unbounded"/>
									</xs:sequence>
								</xs:sequence>
								<xs:attribute name="name" type="tradeNameType" use="required"/>
							</xs:complexType>
						</xs:element>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>

	<xs:simpleType name="nameType">
		<xs:restriction base="xs:string">
			<xs:pattern value="[a-zA-Z0-9]{0,20}"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="tradeNameType">
		<xs:restriction base="xs:string">
			<xs:pattern value="[a-zA-Z0-9]{4}"/>
		</xs:restriction>
	</xs:simpleType>

	<!--内联类型定义 -->
	<xs:simpleType name="inlineType">
		<xs:restriction base="xs:string"/>
	</xs:simpleType>

	<!-- 基础元信息字段名称类型定义 -->
	<xs:simpleType name="fieldNameType">
		<xs:restriction base="nameType"/>
	</xs:simpleType>
	<!-- 基础元信息字段别名类型定义 -->
	<xs:simpleType name="fieldAliasType">
		<xs:restriction base="xs:string">
			<xs:pattern value="[a-zA-Z0-9 _]{0,30}"/>
		</xs:restriction>
	</xs:simpleType>
	<!-- 基础元信息字段类型定义 -->
	<xs:simpleType name="fieldTypeType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="variable"/>
			<xs:enumeration value="fiexd"/>
		</xs:restriction>
	</xs:simpleType>
	<!-- 基础元信息字段描述定义 -->
	<xs:simpleType name="fieldDescType">
		<xs:restriction base="xs:string">
			<xs:pattern value="\w{0,20}"/>
		</xs:restriction>
	</xs:simpleType>
	<!-- 基础元信息字段描述定义 -->
	<xs:simpleType name="fieldLenType">
		<xs:restriction base="xs:integer"/>
	</xs:simpleType>
	<!-- 基础元信息字段Java类型定义 -->
	<xs:simpleType name="fieldClassType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="String"/>
			<xs:enumeration value="Integer"/>
			<xs:enumeration value="BigDecimal"/>
			<xs:enumeration value="Date"/>
		</xs:restriction>
	</xs:simpleType>
	<!-- 基础元信息字段允许为null类型定义 -->
	<xs:simpleType name="fieldAllowNullType">
		<xs:restriction base="xs:boolean"/>
	</xs:simpleType>
	<!-- 基础元信息字段允许为填充样式类型定义 -->
	<xs:simpleType name="fieldFillStyleType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="right"/>
			<xs:enumeration value="left"/>
		</xs:restriction>
	</xs:simpleType>

	<!-- 编码属性定义 -->
	<xs:simpleType name="encodingType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="GBK"/>
			<xs:enumeration value="GB2312"/>
			<xs:enumeration value="ISO8859-1"/>
			<xs:enumeration value="UTF-8"/>
			<xs:enumeration value="Big5"/>
		</xs:restriction>
	</xs:simpleType>

	<!-- 交易数据对象名称属性定义 -->
	<xs:simpleType name="objectNameType">
		<xs:restriction base="xs:string">
			<xs:pattern value="[FO][a-zA-Z0-9]{4}[0-9]|ERR000"/>
		</xs:restriction>
	</xs:simpleType>
	<!-- 交易数据对象类型属性定义 -->
	<xs:simpleType name="objectTypeType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="bean"/>
			<xs:enumeration value="form"/>
		</xs:restriction>
	</xs:simpleType>
	<!-- 交易数据对象描述属性定义 -->
	<xs:simpleType name="objectDescType">
		<xs:restriction base="xs:string">
			<xs:minLength value="0"/>
			<xs:maxLength value="200"/>
		</xs:restriction>
	</xs:simpleType>
	<!-- 交易数据对象编码属性定义 -->
	<xs:simpleType name="objectEncodingType">
		<xs:restriction base="encodingType"/>
	</xs:simpleType>
	<!-- 交易数据对象包装类属性定义 -->
	<xs:simpleType name="objectWrapClassType">
		<xs:restriction base="xs:string"/>
	</xs:simpleType>
	<!-- 交易数据对象字段引用定义 -->
	<xs:complexType name="objectReferFieldType">
		<xs:attribute name="ref"   type="fieldNameType"  use="required"/>
		<xs:attribute name="alias" type="fieldAliasType" use="required"/>
	</xs:complexType>
	<!-- 交易数据对象定义 -->
	<xs:complexType name="objectType">
		<xs:sequence minOccurs="0" maxOccurs="99">
			<xs:element name="field"          type="objectReferFieldType" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="variable-field" type="variableFieldType"    minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="fixed-field"    type="fixedFieldType"       minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute name="name"       type="objectNameType"      use="required"/>
		<xs:attribute name="alias"      type="fieldAliasType"      use="optional"/>
		<xs:attribute name="type"       type="objectTypeType"      use="required"/>
		<xs:attribute name="desc"       type="objectDescType"                     default="对象描述"/>
		<xs:attribute name="encoding"   type="objectEncodingType"  use="optional" default="UTF-8"/>
		<xs:attribute name="wrap-class" type="objectWrapClassType" use="required"/>
	</xs:complexType>
	<!-- 交易数据对象字段引用定义 -->
	<xs:complexType name="referFieldType">
		<xs:attribute name="ref"   type="fieldNameType"  use="required"/>
		<xs:attribute name="alias" type="fieldAliasType" use="required"/>
	</xs:complexType>

	<xs:simpleType name="valueModeType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="constant"/>
			<xs:enumeration value="default"/>
			<xs:enumeration value="user"/>
		</xs:restriction>
	</xs:simpleType>

</xs:schema>

=== zhangyajunsir/abInject/app/cn.com.agree.ab.common/resources/interfaces/HJ19_interface.xml
<?xml version="1.0" encoding="UTF-8"?>
<interfaces 
	xmlns="http://www.w3school.com" 
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
	xsi:schemaLocation="http://www.w3school.com ../xsd/lenovo_sop.xsd">
	<!-- 别名映射，提供对别名和类全限定名之间的映射 -->
	<alias-mappings>
		<!-- domain取值inner和global,inner仅在接口内有效，global在全局有效,在不设置domain时默认为inner -->
		<mapping alias="OHJ190DTO" real="com.woate.talkingbird.dto.OHJ190DTO" domain="inner"/>
		<mapping alias="OHJ191DTO" real="com.woate.talkingbird.dto.OHJ191DTO" />
		<mapping alias="FHJ191DTO" real="com.woate.talkingbird.dto.FHJ191DTO"/>
		<mapping alias="ERR000DTO" real="com.woate.talkingbird.dto.ERR000DTO"  domain="global"/>
		<mapping alias="String" real="java.lang.String" domain="global"/>
		<mapping alias="string" real="java.lang.String" domain="global"/>
		<mapping alias="Date" real="java.util.Date" domain="global"/>
		<mapping alias="BigDecimal" real="java.math.BigDecimal" domain="global"/>
		<mapping alias="Integer" real="java.lang.Integer" domain="global"/>
		<mapping alias="int" real="java.lang.Integer" domain="global"/>
	</alias-mappings>
	<!-- 元信息池，提供对字段集中的定义 -->
	<metadatas-pool>
		<variable-field name="bankNo" encoding="UTF-8" desc="银行卡号" min-len="1" max-len="20" class="String" allow-null="false"/>
		<variable-field name="prodId" encoding="UTF-8" desc="合约代码" min-len="1" max-len="10" class="String" allow-null="true"/>
		<variable-field name="totalAmount" encoding="UTF-8" desc="总笔数" min-len="1" max-len="10" class="Integer" allow-null="false"/>
		<variable-field name="floatProfitAndLoss" encoding="UTF-8" desc="浮动盈亏" min-len="1" max-len="10" class="BigDecimal" allow-null="false"/>
	</metadatas-pool>
	<!-- 交易定义 name不一定是交易码，可能是组合交易的别名-->
	<interface name="HJ19">
		<!-- 请求节点 -->
		<request>
			<!-- 系统信息头 -->
			<sys inline="headers/sys.xml"/>
			<!-- 公共信息头 -->
			<com inline="headers/com.xml"/>
			<busis>
				<!-- 交易数据 name是交易码 -->
				<busi name="HJ19">
					<!-- 交易数据头 -->
					<header inline="headers/busi.xml"/>
					<object name="OHJ190" alias="OHJ190" type="bean" desc="HJ19请求对象" encoding="UTF-8" wrap-class="OHJ190DTO">
						<!-- 对元信息池的定义进行引用 -->
						<field ref="bankNo" alias="bankNo_REQ"/>
						<field ref="prodId" alias="prodId_REQ"/>
					</object>
				</busi>
			</busis>
		</request>
		<!-- 应答节点 -->
		<response>
			<!-- 系统信息头 -->
			<sys inline="headers/sys.xml"/>
			<!-- 公共信息头 -->
			<com inline="headers/com.xml"/>
			<busis>
				<!-- 交易数据 name是交易码 -->
				<busi name="HJ19">
					<!-- 交易数据头 -->
					<header inline="headers/busi.xml"/>
					<object name="OHJ191" alias="OHJ191" type="bean" desc="HJ19应答对象" encoding="UTF-8" wrap-class="OHJ191DTO">
						<field ref="totalAmount" alias="totalAmount_RSP" ></field>
					</object>
					<object name="FHJ191" alias="FHJ191" type="form" desc="HJ19应答表单" encoding="UTF-8" wrap-class="FHJ191DTO">
						<!-- 对元信息池的定义进行引用 -->
						<field ref="prodId" alias="prodId_RSP"/>
						<field ref="floatProfitAndLoss" alias="floatProfitAndLoss_RSP"/>
					</object>
				</busi>
			</busis>
		</response>
		<!--异常节点-->
		<exception>
			<!-- 系统信息头 -->
			<sys inline="headers/sys.xml"/>
			<!-- 公共信息头 -->
			<com inline="headers/com.xml"/>
			<busis>
				<!-- 交易数据 name是交易码 -->
				<busi name="HJ19">
					<!-- 交易数据头 -->
					<header inline="headers/busi.xml"/>
					<object name="ERR000" alias="ERR000" type="bean" desc="错误对象" encoding="UTF-8" wrap-class="ERR000DTO">
						<variable-field name="errorNo" alias="ERROR_NO" desc="错误序号" min-len="0" max-len="0" class="String" allow-null="true"/>
						<variable-field name="errorCode" alias="ERROR_CODE" desc="错误码" min-len="7" max-len="7" class="String" allow-null="true"/>
						<variable-field name="errorMsg" alias="ERROR_MESSAGE" desc="错误信息" min-len="1" max-len="200" class="String" allow-null="true"/>
					</object>
				</busi>
			</busis>
		</exception>
	</interface>
</interfaces>

=== zhangyajunsir/abInject/app/cn.com.agree.ab.common/resources/interfaces/HJ22_interface.xml
<?xml version="1.0" encoding="UTF-8"?>
<interfaces 
	xmlns="http://www.w3school.com" 
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
	xsi:schemaLocation="http://www.w3school.com ../xsd/lenovo_sop.xsd">
	<!-- 别名映射，提供对别名和类全限定名之间的映射 -->
	<alias-mappings>
		<!-- domain取值inner和global,inner仅在HJ19接口内有效，global在全局有效,在不设置domain时默认为inner -->
		<mapping alias="OHJ220DTO" real="com.woate.talkingbird.dto.OHJ220DTO" domain="inner"/>
		<mapping alias="OHJ221DTO" real="com.woate.talkingbird.dto.OHJ221DTO"/>
		<mapping alias="FHJ221DTO" real="com.woate.talkingbird.dto.FHJ221DTO"/>
		<mapping alias="ERR000DTO" real="com.woate.talkingbird.dto.ERR000DTO"  domain="global"/>
		<mapping alias="String" real="java.lang.String" domain="global"/>
		<mapping alias="string" real="java.lang.String" domain="global"/>
		<mapping alias="Date" real="java.util.Date" domain="global"/>
		<mapping alias="BigDecimal" real="java.math.BigDecimal" domain="global"/>
		<mapping alias="Integer" real="java.lang.Integer" domain="global"/>
		<mapping alias="integer" real="java.lang.Integer" domain="global"/>
		<mapping alias="int" real="java.lang.Integer" domain="global"/>
	</alias-mappings>
	<!-- 元信息池，提供对字段集中的定义 -->
	<metadatas-pool>
		<!-- name 字段的名称，alias字段的别名,type字段类型variable不定长，fixed定长, encoding编码集, desc描述，minLen最小长度，maxLen最大长度 len定长长度-->
		<variable-field name="prodId" encoding="UTF-8" desc="合约代码" min-len="7" max-len="10" class="String" allow-null="false"/>
		<variable-field name="startDate" encoding="UTF-8" desc="起始日期" min-len="8" max-len="8" class="Date" allow-null="true"/>
		<variable-field name="endDate" encoding="UTF-8" desc="结束日期" min-len="8" max-len="8" class="Date" allow-null="true"/>
		<variable-field name="startAmount" encoding="UTF-8" desc="起始笔数" min-len="1" max-len="2" class="Integer" allow-null="false"/>
		<variable-field name="selectAmount" encoding="UTF-8" desc="查询笔数" min-len="1" max-len="2" class="Integer" allow-null="false"/>
		<variable-field name="totalAmount" encoding="UTF-8" desc="总笔数" min-len="1" max-len="10" class="Integer" allow-null="true"/>
		<variable-field name="closePrice" encoding="UTF-8" desc="结算价" min-len="1" max-len="2" class="BigDecimal" allow-null="true"/>
		<variable-field name="date" encoding="UTF-8" desc="日期" min-len="1" max-len="2" class="Date" allow-null="true"/>
		<variable-field name="unit" encoding="UTF-8" desc="单位" min-len="1" max-len="2" class="BigDecimal" allow-null="true"/>
	</metadatas-pool>
	<!-- 交易定义 name不一定是交易码，可能是组合交易的别名 他是MainMetadataLoader的名称 -->
	<interface name="HJ22">
		<!-- 请求节点 -->
		<request>
			<!-- 系统信息头 -->
			<sys inline="headers/sys.xml"/>
			<!-- 公共信息头 -->
			<com inline="headers/com.xml"/>
			<busis>
				<!-- 交易数据 name是BusiDataMetadataLoader的名称 -->
				<busi name="HJ22">
					<!-- 交易数据头 -->
					<header inline="headers/busi.xml"/>
					<object name="OHJ220" alias="OHJ220" type="bean" desc="HJ22请求对象" encoding="UTF-8" wrap-class="OHJ220DTO">
						<!-- 对元信息池的定义进行引用 -->
						<field ref="prodId" alias="prodId_REQ"/>
						<field ref="startDate" alias="startDate_REQ"/>
						<field ref="endDate" alias="endDate_REQ"/>
						<field ref="startAmount" alias="startAmount_REQ"/>
						<field ref="selectAmount" alias="selectAmount_REQ"/>
					</object>
				</busi>
			</busis>
		</request>
		<!-- 应答节点 -->
		<response>
			<!-- 系统信息头 -->
			<sys inline="headers/sys.xml"/>
			<!-- 公共信息头 -->
			<com inline="headers/com.xml"/>
			<busis>
				<busi name="HJ22">
					<!-- 交易数据头 -->
					<header inline="headers/busi.xml"/>
					<object name="OHJ221" alias="OHJ221" type="bean" desc="HJ22应答对象" encoding="UTF-8" wrap-class="OHJ221DTO">
						<field ref="totalAmount" alias="totalAmount_RSP"/>
					</object>
					<object name="FHJ221" alias="FHJ221" type="bean" desc="HJ22应答对象" encoding="UTF-8" wrap-class="FHJ221DTO">
						<!-- 对元信息池的定义进行引用 -->
						<field ref="closePrice" alias="closePrice_RSP"/>
						<field ref="date" alias="date_RSP"/>
						<field ref="unit" alias="unit_RSP"/>
					</object>
				</busi>
			</busis>
		</response>
		<!--异常节点-->
		<exception>
			<!-- 系统信息头 -->
			<sys inline="headers/sys.xml"/>
			<!-- 公共信息头 -->
			<com inline="headers/com.xml"/>
			<busis>
				<busi name="HJ22">
					<!-- 交易数据头 -->
					<header inline="headers/busi.xml"/>
					<object name="ERR000" alias="ERR000" type="bean" desc="应答对象" encoding="UTF-8" wrap-class="ERR000DTO">
						<variable-field name="errorNo" alias="ERROR_NO" desc="错误序号" min-len="0" max-len="0" class="String" allow-null="true"/>
						<variable-field name="errorCode" alias="ERROR_CODE" desc="错误码" min-len="7" max-len="7" class="String" allow-null="false"/>
						<variable-field name="errorMsg" alias="ERROR_MESSAGE" desc="错误信息" min-len="1" max-len="200" class="String" allow-null="false"/>
					</object>
				</busi>
			</busis>
		</exception>
	</interface>
</interfaces>
